ToonYou:
  base: ""
  path: "models/DreamBooth_LoRA/toonyou_beta3.safetensors"
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  seed:           [10788748646984564526, 6520604545582963616]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "best quality, masterpiece, 1girl, wedding dress, black page-boy hair, black eyes, blue sky, white clouds, spring season, upper body,  outdoors, falling petals"
    - "best quality, masterpiece, 1girl, wedding dress, black page-boy hair, black eyes, night, white moon, spring season, upper body,  outdoors, falling petals"
  n_prompt:
    - ""
    - "badhandv4,easynegative,ng_deepnegative_v1_75t,verybadimagenegative_v1.3, bad-artist, bad_prompt_version2-neg, teeth"
    - ""
    - ""
