GhibliBackground:
  base: "models/DreamBooth_LoRA/CounterfeitV30_v30.safetensors"
  path: "models/DreamBooth_LoRA/lora_Ghibli_n3.safetensors"
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  seed:           [877618]
  steps:          25
  guidance_scale: 7.5
  lora_alpha: 1.0

  prompt:
    - "best quality, masterpiece, volcano, volcanic eruption"

  n_prompt:
    - "imaginary, exerlent"
